"""State operations for the POSTULATED finite-penalty projector Hamiltonian.

Gauge invariance (A_v psi=psi), probability continuity, and the energetic cost of
an A_v violation are distinct statements. This module implements H=-sum A-sum B
on the unrestricted edge Hilbert space. Its commuting terms freeze all defect
syndromes. String interventions are not autonomous evolution generated by H.
"""

import numpy as np


class DefectDynamics:
    """Matrix-free actions on an already enumerated small GaugePatch."""

    def __init__(self, patch):
        if patch.configs is None:
            raise ValueError('DefectDynamics requires an enumerated small patch')
        self.patch = p = patch
        self.perms = {v: [p.gauge_permutation(v, h) for h in range(p.n)] for v in p.vertices}
        self.flat_masks = {f: p.holonomy(f) == p.e_id for f in p.faces}

    def _state(self, state):
        state = np.asarray(state, dtype=complex)
        if state.shape != (self.patch.dim,):
            raise ValueError('state must be a vector on the full patch configuration space')
        return state

    def star(self, vertex, state):
        state = self._state(state)
        out = np.zeros_like(state)
        for perm in self.perms[vertex]:
            out[perm] += state / self.patch.n
        return out

    def plaquette(self, face, state):
        return self.flat_masks[face] * self._state(state)

    def hamiltonian(self, state):
        state = self._state(state)
        out = np.zeros_like(state)
        for v in self.patch.vertices:
            out -= self.star(v, state)
        for f in self.patch.faces:
            out -= self.plaquette(f, state)
        return out

    def flat_vacuum(self):
        """Uniform flat superposition; not a uniqueness claim on arbitrary topology."""
        support = np.ones(self.patch.dim, bool)
        for mask in self.flat_masks.values():
            support &= mask
        state = support.astype(complex)
        return state / np.linalg.norm(state)

    def evolve(self, state, time):
        """Exact exp(-itH) via exp(itP)=I+(exp(it)-1)P; no Trotter approximation."""
        if not np.isfinite(time):
            raise ValueError('time must be finite')
        state = self._state(state).copy()
        coefficient = np.expm1(1j * time)
        for v in self.patch.vertices:
            state += coefficient * self.star(v, state)
        for f in self.patch.faces:
            state += coefficient * self.plaquette(f, state)
        return state

    def string_factor(self, path, character):
        """Unitary electric string from a 1D character; excludes matrix-valued irreps.

        Its diagonal phase is chi of oriented path holonomy. Equality for two
        paths is asserted only on states flat across the intervening contractible
        faces, not as an identity on the whole Hilbert space.
        """
        p = self.patch
        character = np.asarray(character, dtype=complex)
        if (character.shape != (p.n,) or not np.allclose(np.abs(character), 1, atol=1e-12, rtol=0)
                or not np.allclose(character[p.mul], character[:, None] * character[None, :], atol=1e-12, rtol=0)):
            raise ValueError('a unit-modulus one-dimensional group character is required')
        if len(path) < 2:
            raise ValueError('path needs at least one edge')
        hol = np.full(p.dim, p.e_id, dtype=int)
        for a, b in zip(path, path[1:]):
            key = (min(a, b), max(a, b))
            if key not in p.eindex:
                raise ValueError(f'path edge {key} is absent from the patch')
            lab = p.configs[:, p.eindex[key]]
            if a > b:
                lab = p.inv[lab]
            hol = p.mul[hol, lab]
        return character[hol]

    def readout(self, state):
        state = self._state(state)
        norm2 = float(np.vdot(state, state).real)
        if norm2 == 0:
            raise ValueError('cannot read probabilities from the zero vector')
        stars = {str(v): float(np.vdot(state, self.star(v, state)).real / norm2) for v in self.patch.vertices}
        faces = {str(f): float(np.vdot(state, self.plaquette(f, state)).real / norm2) for f in self.patch.faces}
        return {'norm2': norm2, 'star_expectations': stars, 'flatness_expectations': faces,
                'energy': -sum(stars.values()) - sum(faces.values())}
