"""Option A at small scale: the v4.0 walk with a *quantum* record on a few edges.

(DYNAMICS_DESIGN section 10; PREDICTIONS P21.)

State Psi[arc, c, i]. c indexes the joint record basis |g_1 ... g_k> of the k quantum
edges (12**k states); every other edge is frozen at the identity (flat vacuum).
One fixed unitary per tick:

    U = U_rec . U_walk
    U_walk : v4.0 walk (coin 2|phi><phi| - I, transported shift), controlled on the record:
             an arc across a quantum edge is transported by rho of that basis label.
    U_rec  : exp(-i lB W/2) . (x)_e exp(-i lE L_e / 8) . exp(-i lB W/2)
             L_e : group Laplacian generated by the 8 order-3 elements (class union)
             W   : sum over faces touching a quantum edge of (1 - chi_3(hol)/3)

Quasi-energy of the whole is conserved because U is fixed; ``unstep`` inverts a tick.
This is a *partial* quantum record (frozen edges elsewhere): gauge invariance holds only
for gauge moves that leave frozen edges alone. Kernel-pure: no RNG.
"""

import numpy as np
from scipy.linalg import expm, schur

from .walk import ArcWalk, a4_irrep3


class QuantumRecordWalk:
    def __init__(self, cx, qedges, lam_E, lam_B, ring_weights=(1.0, 0.5), mode="closed"):
        g = cx.group
        self.cx, self.g = cx, g
        self.els = list(g.elements)
        self.eidx = {x: i for i, x in enumerate(self.els)}
        self.e_id = self.eidx[g.identity()]
        rep = a4_irrep3(g)
        self.rep = rep
        self.R = np.array([rep(x) for x in self.els])                  # (12,3,3)
        self.mode = mode
        self.walk = w = ArcWalk(cx, rep=None, dim=1, mode=mode, ring_weights=ring_weights)
        self.qedges = [tuple(sorted(e)) for e in qedges]
        self.k = k = len(self.qedges)
        self.nc = 12 ** k
        self.qarcs = []                                               # (axis, arc a->b, arc b->a)
        for ax, (a, b) in enumerate(self.qedges):
            if cx.label(a, b) != g.identity():
                raise ValueError("frozen vacuum expects identity labels")
            iab, iba = w.index.get((a, b)), w.index.get((b, a))
            if iab is None or iba is None:
                raise ValueError("quantum edges must join interior vertices")
            self.qarcs.append((ax, iab, iba))
        # plain arcs: transport identity
        qset = {i for _, i, j in self.qarcs} | {j for _, i, j in self.qarcs}
        self.plain = np.array([a for a in range(len(w.arcs)) if w.kept[a] and a not in qset])
        n = len(w.arcs)
        # src[j]: the arc whose amplitude arrives on arc j (n = a zero row: nothing arrives)
        self.src = np.full(n, n)
        self.src[w.target[w.kept]] = np.nonzero(w.kept)[0]
        self.lost = np.nonzero(~w.kept)[0]                       # arcs into the open boundary
        if mode == "closed" and not np.array_equal(w.target[w.target], np.arange(n)):
            raise ValueError("closed box expected: every arc has its reverse")
        # --- record Hamiltonian pieces
        order3 = [i for i, x in enumerate(self.els) if g.order_of(x) == 3]
        mul = np.array([[self.eidx[g.multiply(x, y)] for y in self.els] for x in self.els])
        self.mul = mul
        L = np.zeros((12, 12))
        for s in order3:
            for gi in range(12):
                L[gi, gi] += 1
                L[mul[s, gi], gi] -= 1
        self.L8 = L / 8.0
        self.chi = np.trace(self.R, axis1=1, axis2=2)
        self.W = self._wilson()
        self.lam_E, self.lam_B = lam_E, lam_B
        self.E1 = expm(-1j * lam_E * self.L8)
        self.half = np.exp(-0.5j * lam_B * self.W)
        self._bufs = {}
        self.vac = self._vacuum()

    # ------------------------------------------------------------------ record pieces
    def _config_labels(self):
        idx = np.indices((12,) * self.k).reshape(self.k, -1)           # (k, nc)
        return idx

    def _wilson(self):
        g, cx = self.g, self.cx
        qpos = {e: ax for ax, e in enumerate(self.qedges)}
        faces = [f for f in cx.faces() if any(tuple(sorted(p)) in qpos
                                                for p in ((f[0], f[1]), (f[1], f[2]), (f[0], f[2])))]
        self.faces = faces
        labs = self._config_labels()
        W = np.zeros(self.nc)
        inv = [self.eidx[g.inverse(x)] for x in self.els]
        for f in faces:
            h = np.full(self.nc, self.e_id)
            for u, v in ((f[0], f[1]), (f[1], f[2]), (f[2], f[0])):
                key = (min(u, v), max(u, v))
                if key in qpos:
                    lab = labs[qpos[key]]
                    if (u, v) != key:
                        lab = np.array(inv)[lab]
                    h = self.mul[h, lab]
            W += 1 - self.chi[h] / 3.0
        return W

    def _along(self, M, X, ax):
        """Apply the 12x12 matrix M on record axis ax of X shaped (A, 12,..,12, B)."""
        return np.moveaxis(np.tensordot(M, X, axes=([1], [ax + 1])), 0, ax + 1)

    def _buf(self, name, like):
        b = self._bufs.get(name)
        if b is None or b.shape != like.shape or b.dtype != like.dtype:
            b = self._bufs[name] = np.empty_like(like)
        return b

    def apply_rec(self, Psi, inverse=False):
        """U_rec (or its inverse) on the record index of Psi (A, nc, B). Returns a new array."""
        half = self.half.conj() if inverse else self.half
        E = self.E1.conj().T if inverse else self.E1
        A, nc, B = Psi.shape
        k = self.k
        X = half[None, :, None] * Psi
        Y = np.empty_like(X)
        for ax in range(k):
            pre, post = 12 ** ax, 12 ** (k - 1 - ax) * B
            np.matmul(E, X.reshape(A * pre, 12, post), out=Y.reshape(A * pre, 12, post))
            X, Y = Y, X
        X *= half[None, :, None]
        return X

    def apply_H(self, Psi):
        A, _, B = Psi.shape
        X = Psi.reshape((A,) + (12,) * self.k + (B,))
        out = sum(self._along(self.L8, X, ax) for ax in range(self.k))
        return self.lam_E * out.reshape(Psi.shape) + self.lam_B * self.W[None, :, None] * Psi

    def rec_matrix(self):
        M = np.eye(self.nc, dtype=complex)[None]
        return self.apply_rec(M)[0]


    def _vacuum(self):
        e0 = np.zeros(self.nc, complex)
        e0[np.ravel_multi_index((self.e_id,) * self.k, (12,) * self.k)] = 1
        if self.lam_E == 0:
            return e0
        T, Z = schur(self.rec_matrix(), output="complex")
        ev = np.diag(T)
        amp = Z.conj().T @ e0
        j = np.argmax(np.abs(amp))
        cl = np.abs(ev - ev[j]) < 1e-9
        v = Z[:, cl] @ amp[cl]
        return v / np.linalg.norm(v)

    # ------------------------------------------------------------------ walker pieces
    def _transport(self, X, ax, inverse_label):
        """Apply rho(g) (or rho(g)^-1) per record basis label on axis ax. X: (nc, 3)."""
        R = np.transpose(self.R, (0, 2, 1)) if inverse_label else self.R
        Xk = X.reshape((12,) * self.k + (3,))
        Xk = np.moveaxis(Xk, ax, 0)
        Y = np.einsum("gij,g...j->g...i", R, Xk)
        return np.moveaxis(Y, 0, ax).reshape(X.shape)

    def walk_step(self, Psi):
        """One walk tick. In open mode the amplitude on arcs into the boundary leaves;
        it is available afterwards as ``self.escaped`` (the coined amplitude on those arcs)."""
        w = self.walk
        n = len(w.arcs)
        shape = (n + 1,) + Psi.shape[1:]
        B = self._bufs.get("B")
        if B is None or B.shape != shape or B.dtype != Psi.dtype:
            B = self._bufs["B"] = np.zeros(shape, Psi.dtype)
        Bn = B[:n]
        np.multiply(w.phi[:, None, None], Psi, out=Bn)
        ov = np.add.reduceat(Bn, w.starts, axis=0)
        np.take(ov, w.vertex_of_arc, axis=0, out=Bn)
        Bn *= 2 * w.phi[:, None, None]
        Bn -= Psi                                  # coined state; B[n] stays zero
        self.escaped = Bn[self.lost].copy() if len(self.lost) else None
        out = np.take(B, self.src, axis=0)
        for ax, iab, iba in self.qarcs:
            # arc a->b uses rho(label(b,a)) = rho(g)^-1 ; arc b->a uses rho(g)
            out[w.target[iab]] = self._transport(Bn[iab], ax, True)
            out[w.target[iba]] = self._transport(Bn[iba], ax, False)
        return out

    def walk_unstep(self, Psi):
        if self.mode != "closed":
            raise ValueError("unstep needs the closed box (open mode loses amplitude)")
        w = self.walk
        cps = np.empty_like(Psi)
        cps[self.plain] = Psi[w.target[self.plain]]
        for ax, iab, iba in self.qarcs:
            cps[iab] = self._transport(Psi[w.target[iab]], ax, False)
            cps[iba] = self._transport(Psi[w.target[iba]], ax, True)
        ov = np.add.reduceat(w.phi[:, None, None] * cps, w.starts, axis=0)
        return 2 * w.phi[:, None, None] * ov[w.vertex_of_arc] - cps   # coin is an involution

    def step(self, Psi, record=True):
        Psi = self.walk_step(Psi)
        return self.apply_rec(Psi) if record else Psi

    def unstep(self, Psi, record=True):
        if record:
            Psi = self.apply_rec(Psi, inverse=True)
        return self.walk_unstep(Psi)

    def product_state(self, psi_walker):
        return psi_walker[:, None, :] * self.vac[None, :, None]
